# The numpy.random package in Python

## Student: Zara Quail G00376517

## Programming for Data Analytics Assignment 11 November 2019

### 1. The overall purpose of the numpy.random package

The numpy.random is a sub-package of the numpy Python package that is designed to generate pseudo random numbers or arrays of numbers.[1,2] It does so by combining sequences from a BitGenerator with samples from different statistical distributions sampled by a Generator.[2] A BitGenerator is an object that is used to generate random numbers or sequences.[2]  Sequences of random bits from a BitGenerator are then transformed by a Generator into sequences of numbers that are in a specific probability distribution inside a specified interval.[2] 

### 2. The use of the "Simple random data" and "Permutations" functions

#### Simple random data
Simple random data functions are used to return random values, samples, integers, floats or bytes from various set intervals, distributions or arrays.[3]

For example the rand fuction presents an array of random numbers between 0 and 1 in a specific shape.[3]

In [12]:
import numpy as np
import matplotlib.pyplot as plt

In [13]:
np.random.rand(3,2)

array([[0.90146165, 0.14271051],
       [0.3565442 , 0.17472977],
       [0.39381941, 0.974553  ]])

In [14]:
np.random.rand(4)

array([0.15260228, 0.99159718, 0.46837356, 0.65128828])

There are further variations on the simple random data functions for which I demonstrate the examples below.[3]

##### randn function 
The randn function is demonstrated below showing how this function returns a sample/s from the "standard normal" distribution.[3]
A single float is randomly sampled from the distribution if no argument is provided for rhe randn function.[3] For example:[3]

In [16]:
np.random.randn()

0.46368215865121565

If arguments are inserted, then the randn function creates an array of shape filled with random floats taken from a univariate "normal" distribution in which the mean is 0 with a variance of 1.[3] For example:[3]

In [17]:
2.5 * np.random.randn(2, 4) + 3

array([[1.06066274, 0.26065519, 1.27837753, 3.30748372],
       [2.28363859, 1.16417649, 2.63239221, 6.94101817]])

#### Permutations
Permutations function is used for..... It has two functions, namely: shuffle and permutation.[3, 4]

### 3. The use and purpose of at least five "Distributions" functions

#### beta
The beta distribution code is (a, b[, size]) and is used to draw samples from a Beta distribution.[3]

#### geometric

The geometric distribution code is (p[, size]) and is used to draw samples from the geometric distribution.[3]



#### normal

The normal distribution code is ([loc, scale, size]) and is used to draw random samples from a normal (Gaussian) distribution.[3]

#### triangular

The triangular distribution code is (left, mode, right[, size]) and is used to draw samples from the triangular distribution over the interval [left, right]. [3]

#### gumbel

The gumbel distribution code is ([loc, scale, size]) and is used to draw samples from a Gumbel distribution.[3]



### 4. The use of seeds in generating pseudorandom numbers

### References

1. Ian Mcoughlin. Introduction to numpy.random. 2018. Available from: https://web.microsoftstream.com/video/ea6519e9-f7ed-444c-9b25-d855dfaa363a (Access date: 10 November 2019)
2. NumPy.org. Random sampling (numpy.random). NumPy v1.17rc1 Manual. 2019. Available at: https://numpy.org/doc/1.17/reference/random/index.html (Access date: 10 November 2019)
3. SciPy.org. Random sampling (numpy.random). NumPy v1.15 Manual. 2018. Available at: https://docs.scipy.org/doc/numpy-1.15.0/reference/routines.random.html (Access date: 10 November 2019)
4. NumPy.org. Random Generator. NumPy v1.17rc1 Manual. 2019 Available at: https://numpy.org/doc/1.17/reference/random/generator.html (Access date: 10 November 2019)